export const EXTENSION_FILES = Object.freeze([
  'manifest.json',
  'background.js',
  'background/settings-service.js',
  'background/command-service.js',
  'background/image-service.js',
  'background/bili-session-service.js',
  'background/network-service.js',
  'background/zhihu-sync-service.js',
  'background/tab-coordinator.js',
  'background/message-router.js',
  'content.js',
  'docs-viewer.html',
  'docs-viewer.js',
  'README.md',
  'README_EN.md',
  'ARCHITECTURE.md',
  'ARCHITECTURE_EN.md',
  'CHANGELOG.md',
  'PRIVACY_POLICY.md',
  'LICENSE',
  'core/messages.js',
  'core/settings.js',
  'core/input-policy.js',
  '_locales/zh_CN/messages.json',
  '_locales/en/messages.json',
  'icons/icon16.png',
  'icons/icon48.png',
  'icons/icon128.png',
  'icons/icon300.png',
  'common/keyboard-enhance.js',
  'common/input-context.js',
  'common/lowpoly-bg.js',
  'common/mouse-gesture.js',
  'common/super-drag.js',
  'search-box/search-box.js',
  'ntp/blank-critical.css',
  'ntp/blank-init.js',
  'ntp/ntp.css',
  'ntp/ntp.html',
  'ntp/ntp.js',
  'ntp/modules/wallpaper-domain.js',
  'ntp/modules/wallpaper-state.js',
  'ntp/modules/wallpaper-data-source.js',
  'ntp/modules/wallpaper-image-processor.js',
  'ntp/modules/custom-wallpaper-controller.js',
  'ntp/modules/wallpaper-command-controller.js',
  'ntp/modules/wallpaper-status-view.js',
  'ntp/modules/wallpaper-settings-controller.js',
  'ntp/modules/wallpaper-collection-controller.js',
  'ntp/modules/wallpaper-page-controller.js',
  'ntp/modules/wallpaper-sync-controller.js',
  'ntp/modules/wallpaper-theme.js',
  'ntp/modules/notification-view.js',
  'ntp/modules/wallpaper-info-controller.js',
  'ntp/modules/wallpaper-renderer.js',
  'ntp/modules/wallpaper-cache.js',
  'ntp/modules/wallpaper-repository.js',
  'ntp/modules/trending-controller.js',
  'ntp/modules/search-controller.js',
  'ntp/modules/zoom-controller.js',
  'ntp/modules/input-adapter.js',
  'ntp/modules/lowpoly-adapter.js',
  'ntp/modules/blank-mode-controller.js',
  'ntp/modules/startup.js',
  'options/options.css',
  'options/options.html',
  'options/options.js',
  'fre/fre.js',
  'fre/input-demo.js',
  'fre/fre-step1.html',
  'fre/fre-step1.js',
  'fre/fre-step2.html',
  'fre/fre-step2.js',
  'fre/fre-step3.html',
  'fre/fre-step4.html',
  'bili-tool/bili-tool.js',
  'bili-feed-history/bili-feed-history.js',
  'zhihu-tool/zhihu-tool.js',
  'website/wallpaper-data.json',
  'website/images/bili.webp',
  'docs/images/bookmark-bar-cascade.mp4',
  'docs/images/fre-step3-playground.mp4',
  'docs/images/searchbox-pulse-rings.mp4',
  'docs/images/wallpaper-theme-adapt.mp4'
]);

export const FORBIDDEN_PACKAGE_PREFIXES = Object.freeze([
  '.git/',
  '.github/',
  '.vscode/',
  'coverage/',
  'crawler/',
  'node_modules/',
  'scripts/',
  'tests/'
]);

export function normalizePackagePath(filePath) {
  return filePath.replaceAll('\\', '/').replace(/^\.\//, '');
}

export function isAllowedExtensionFile(filePath) {
  return EXTENSION_FILES.includes(normalizePackagePath(filePath));
}

export function isForbiddenPackageFile(filePath) {
  const normalized = normalizePackagePath(filePath);
  return FORBIDDEN_PACKAGE_PREFIXES.some((prefix) => normalized.startsWith(prefix));
}